### ISSUE TITLE
Byte_sequence.length in Archive is slow

### ISSUE THREAD

**Issue by emersion** [rems-project/linksem#8]
In `Archive.accum_archive_contents`, the first line computes the byte sequence length:

https://github.com/rems-project/linksem/blob/d3ca79eab80c1dfe3228dfe51b5e882557b22046/src/archive.lem#L69

This is a performance bottleneck: by removing it, execution time goes from 17s to 11s on a glibc-linked hello world.

I wonder what's the best way to deal with it:
* Make the ocaml target omit the check somehow? Maybe there's a way to disable `assert`s with release builds?
* Switch `Byte_sequence` to be backed by an array instead of a list for the ocaml target. This will probably increase performance on the whole codebase, not sure how tricky it is.

**Comment by stephenrkell** [comment]
We agreed that trying the array approach is a good one, if it proves not too annoying.

It will be interesting to see whether arrays bring their own bottlenecks or not. I suspect the "ultimate solution" would be using a more clever hybrid, like a rope, perhaps for all Lem lists in the OCaml back-end.
